### ISSUE TITLE
Support for non '/' SPA Root

### ISSUE THREAD

**Issue by john-hadron** [metakermit/django-spa#2]
Hi,

Thanks for the awesome work!

Is there any plan to support non "/" or "/index.html" spa roots?

In my use case, my spa root is at "/dashboard", while my "/" is a plain old regular django template.

Cheers,

**Comment by metakermit** [comment]
Hey @john-hadron sorry for the late reply. The idea is pretty good, but I didn't really have time to look into it yet. I'll try to add this feature when I get to the next round of updates to the library. Cheers!

**Comment by metakermit** [comment]
Closing this for now as I'm trying to keep up with the core set of features.
