### ISSUE TITLE
Django-React - No CSRF Cookie Set

### ISSUE THREAD

**Issue by samuelthng** [metakermit/django-spa#24]
* django-spa version:
* Python version:
* Operating System:

### Description

I have the requirement to get a CSRF cookie set but can't find a way to inject the token.

### What I Did

Just use CRA with a script to copy the build folder into the static folder for the Django site after build.

**Comment by metakermit** [comment]
Hey Samuel, I suggest you try [one of these solutions suggested in the Django docs](https://docs.djangoproject.com/en/2.1/ref/csrf/#scenarios) to disable CSRF protection for some views you need to use for your API. Django REST framework probably also has ways of achieving this.

**Comment by samuelthng** [comment]
Hey metakermit,

That's exactly what I've done as a workaround.

I currently expose an API that sends a 204 but sets the CSRF cookie.
Dirty but it works for what I need right now.

<details><summary>Implementation</summary>

```
from django.http import HttpResponse
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt

@csrf_exempt
@ensure_csrf_cookie
def setCSRF(request):
    return HttpResponse(status=204)
```
On React, it's just a simple fetch to make that query and the cookie is set. </details>

Thanks @metakermit!

**Comment by metakermit** [comment]
No problem. I’ll look into making an example that demonstrates this for
others. Cheers!
