### ISSUE TITLE
How to set custom name for static files directory?

### ISSUE THREAD

**Issue by DanielKucal** [metakermit/django-spa#26]
* django-spa version: 0.2.0
* Python version: 3.7
* Operating System: various

### Description

My hosting forces me to keep static files in `public/static/` directory, which does not seem to work with this library. Is there a way to change it?

**Comment by metakermit** [comment]
Hey Daniel. Not out of the box unfortunately. The config to get all of this working is pretty fiddly, so I tried to keep everything as default as possible.

The best solution would be to try and fork the repo and change the path yourself. I'd be happy to accept a PR for this if you manage to make it configurable. Have a nice day!

**Comment by DanielKucal** [comment]
I ended up using Angular's index.html inside Django's templates and following URL pattern:
```
url(r'^.*$', TemplateView.as_view(template_name="index.html")),
```
