### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by BlackXnt** [metakermit/django-spa#36]
* django-spa version: 0.2.0
* Python version: 3.8.0
* Operating System: Windows

This package requires using whitenoise 3.2.2, which doesn't work with django 3.0.
Is this repository still maintained?

**Comment by metakermit** [comment]
You're right. I'll release a new version shortly.

**Comment by BlackXnt** [comment]
Thank you!

Are you planning to upload the new version to pypi?

**Comment by metakermit** [comment]
Yeah, I will do that. Hopefully within a day or so max. I tried to do it
right away, but it seems something broke with my auto-deploy config, so I
have to fix it first.

**Comment by metakermit** [comment]
@BlackXnt OK, it's [up now](https://pypi.org/project/django-spa/0.3.5/). Let me know if you experience any further bugs.
