### ISSUE TITLE
Conflicting dependencies error message (whitenoise 5.2.0 vs. django-spa 0.3.5)

### ISSUE THREAD

**Issue by VBobCat** [metakermit/django-spa#45]
This is about django-spa 0.3.5. I'm running Python 3.8.5 on Windows 10 64bits.

When running `pip install -r requirements.txt --use-feature 2020-resolver` for my project dependencies, I receive this message:

```
ERROR: Cannot install whitenoise==5.2.0 and django-spa 0.3.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested whitenoise==5.2.0
    django-spa 0.3.5 depends on whitenoise==5.0.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

Is there any actual breaking incompatibility caused by whitenoise versions later than 5.0.1, which is the one required by django-spa 0.35?

**Comment by MarcoGlauser** [comment]
We have the same issue.
It seems like there were only small changes between the releases, so it should be fairly safe to upgrade
https://github.com/evansd/whitenoise/compare/v5.0.1...v5.2.0

**Comment by metakermit** [comment]
Fixed in https://github.com/metakermit/django-spa/pull/60
